import { Component, OnInit, ViewChild } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { IHeaderMap, ColumnFilterService, ApiESaleyardService } from '@app/core';
import { CustomizedGridComponent } from '@app/shared';
import { environment } from '@env/environment';
import { UserDetail } from '@app/core/models/user-detail';

@Component({
  selector: 'app-billing-document-log-modal',
  templateUrl: './billing-document-log-modal.component.html',
  styleUrls: ['./billing-document-log-modal.component.scss']
})
export class BillingDocumentLogModalComponent implements OnInit {

  @ViewChild(CustomizedGridComponent)
  private gridView: CustomizedGridComponent;

  dataSource: any = [];
  itemsCount: number;
  bodyData = {
    DocumentNumbers: '',
    PageSize: 10,
    PageNumber: 0,
    SortColumn: '-1',
    SortOrder: 'desc',
    TimeZone: 0,
    GridFilters: []
  };


  filters: any = {};

  headerMap: IHeaderMap = {
    config: {
      header: {
        columns: [
          {
            objectKey: 'DocumentNumber',
            displayName: 'Document Number'
          },
          {
            objectKey: 'DocumentType',
            displayName: 'Document Type'
          },
          {
            objectKey: 'GeneratedOn',
            displayName: 'Generated On',
            dataType: 'Date',
            format: environment.Setting.dateTimeFormat,
            timeZone: this.userDetail.TimeZone.toString()
          },
          {
            objectKey: 'CustomerEmail',
            displayName: 'Customer Email'
          },
          {
            objectKey: 'GeneratedBy',
            displayName: 'Generated By'
          },
          {
            objectKey: 'DeliveryMode',
            displayName: 'Delivery Mode'
          }
        ],
        action: {
        },
        columnFilter: []
      },
      paging: true
    }
  };


  constructor(
    public activeModal: NgbActiveModal,
    private api: ApiESaleyardService,
    private columnFilter: ColumnFilterService,
    private userDetail: UserDetail
  ) { }

  ngOnInit() {
    this.getDataSource();
  }

  async generateFilter() {
    this.bodyData.GridFilters = [];
    this.bodyData.PageNumber = 0;
    Object.keys(this.filters).forEach(key => {
      this.bodyData.GridFilters.push(this.filters[key]);
    });
    await this.getDataSource();
    this.gridView.currentPage = 1;
  }

  async getDataSource() {
    let response: any;
    response = await this.api.post('report/getBillingDocumentLog', this.bodyData).toPromise();

    this.dataSource = response.Data;
    this.itemsCount = response.RecordsCount;
  }

  pageChange(event) {
    this.bodyData.PageNumber = event.currentPage - 1;
    this.bodyData.PageSize = event.pageSize;
    this.getDataSource();
  }

  bindColumnFilterDdl(item) {
    let type = '';
    if (item.colData.dataType === 'Date') {
      type = 'DateEditBox';
    }
    const FilterData = this.columnFilter.GetFilterByDataType(type); // Calling Function to get ColumnFilter Condition data
    if (FilterData.length === 0) { // Check if Array is empty then call API for options data
    } else {
      this.headerMap.config.header.columnFilter['colData_' + item.colIndex] = FilterData;
    }
  }


  actionClick(event: any) {
    switch (event.action) {
      case 'Filter_Header':
        this.bindColumnFilterDdl(event);
        break;
      case 'Filter_Click':
        let filter: any = {};
        filter = {
          GridConditions: [],
          DataField: event.colData.objectKey,
          LogicalOperator: event.filterData.logicalOpt.Value === 'Select...' ? '' : event.filterData.logicalOpt.Value,
          FilterType: 'Column_Filter'
        };
        if (event.filterData.filterValue1 && event.filterData.filterValue1 !== '') {
          filter.GridConditions.push({
            Condition: event.filterData.ConditionOpt1.Value,
            ConditionValue: event.filterData.filterValue1
          });
        }
        if (event.filterData.filterValue2 && event.filterData.filterValue2 !== '') {
          filter.GridConditions.push({
            Condition: event.filterData.ConditionOpt2.Value,
            ConditionValue: event.filterData.filterValue2
          });
        }
        if (filter && Object.keys(filter).length !== 0) {
          this.filters['Column_Filter~$~' + event.colData.objectKey] = filter;
        }
        this.generateFilter();
        event.ColumnFilterDropdown.close();
        break;
      case 'asc':
        this.bodyData.SortColumn = event.colData.objectKey;
        this.bodyData.SortOrder = 'asc';
        this.getDataSource();
        break;
      case 'desc':
        this.bodyData.SortColumn = event.colData.objectKey;
        this.bodyData.SortOrder = 'desc';
        this.getDataSource();
        break;
      case 'Remove Sort':
        this.bodyData.SortColumn = '-1';
        this.bodyData.SortOrder = 'desc';
        this.getDataSource();
        break;
      case 'FilterClear_Click':
        delete this.filters['Column_Filter~$~' + event.colData.objectKey];
        this.generateFilter();
        event.ColumnFilterDropdown.close();
        break;
    }
  }

}
